<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311221928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE animal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, race VARCHAR(255) NOT NULL, sexe VARCHAR(100) NOT NULL, date_naissance DATE NOT NULL, status VARCHAR(100) NOT NULL, sterilise BOOLEAN NOT NULL, identification_number VARCHAR(100) NOT NULL, poil VARCHAR(255) NOT NULL, date_identification DATE NOT NULL, pays_naissance VARCHAR(255) NOT NULL, categorie VARCHAR(255) NOT NULL, livre_origines BOOLEAN NOT NULL, signes_particuliers VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AAB231F7E3C61F9 ON animal (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6AAB231F4ACC9A20 ON animal (card_id)');
        $this->addSql('CREATE TABLE identification_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_edition TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, emplacement VARCHAR(255) NOT NULL, signes_particuliers VARCHAR(255) DEFAULT NULL, pays_naissance VARCHAR(255) NOT NULL, pdf_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, civilite VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, code_postal VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, profile_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE animal ADD CONSTRAINT FK_6AAB231F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE animal ADD CONSTRAINT FK_6AAB231F4ACC9A20 FOREIGN KEY (card_id) REFERENCES identification_card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE animal DROP CONSTRAINT FK_6AAB231F7E3C61F9');
        $this->addSql('ALTER TABLE animal DROP CONSTRAINT FK_6AAB231F4ACC9A20');
        $this->addSql('DROP TABLE animal');
        $this->addSql('DROP TABLE identification_card');
        $this->addSql('DROP TABLE "user"');
    }
}
